Feat/Add Snapshot Classes
wizeline/factiva-news-javascript pull request #1
Opened 2021-06-17 07:36 UTC by cerritows

## Description
Add functionality to handle taxonomy and Snapshots endpoints.

2021-06-17 15:51 UTC, germfy approved these changes
🕺🏼

2021-06-17 23:24 UTC, vic3r requested changes
Some small changes can be done

2021-06-17 23:24 UTC, vic3r commented on src/factiva/news/snapshot/snapshot.js
> +        snapshot.userKey = await UserKey.create(userKey, requestInfo);
same here

2021-06-17 23:24 UTC, vic3r commented on src/factiva/news/taxonomy/index.js
> +        taxonomy.categories = await taxonomy.getCategories();
same here for both cases

2021-06-18 04:47 UTC, cerritows commented on src/factiva/news/bulkNews.js
> +
No, because `constants` is not being exported in any `index` file. This is meant to be temporary while the `core` package structure is defined.

2021-06-18 04:48 UTC, cerritows commented on src/factiva/news/bulkNews.js
> +        const job = new BulkNewsJob();
Good catch! 💯

2021-06-21 21:37 UTC, vic3r approved these changes
👍

2021-06-22 01:06 UTC, merged